---

apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ printf "%s-unbound" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
    namespace: {{ include "common.names.namespace" . | quote }}
    labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 6 }}
    {{- if .Values.commonAnnotations }}
    annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 6 }}
    {{- end }}
data:
    options.inc: |
        dns {
            nameserver = "master-slave:127.0.0.1,8.8.8.8";
        }

    unbound.conf: |
        server:
            cache-max-ttl: 86400
            cache-min-ttl: 300
            directory: "/opt/unbound/etc/unbound"
            do-ip4: yes
            do-ip6: no
            do-tcp: yes
            do-udp: yes
            edns-buffer-size: 1232
            interface: 0.0.0.0@53
            port: 53
            prefer-ip6: no
            rrset-roundrobin: yes
            username: "_unbound"
            log-local-actions: no
            log-queries: no
            log-replies: no
            log-servfail: no
            logfile: /dev/null
            verbosity: 0
            infra-cache-slabs: 4
            incoming-num-tcp: 10
            key-cache-slabs: 4
            msg-cache-size: 142768128
            msg-cache-slabs: 4
            num-queries-per-thread: 4096
            num-threads: 3
            outgoing-range: 8192
            rrset-cache-size: 285536256
            rrset-cache-slabs: 4
            minimal-responses: yes
            prefetch: yes
            prefetch-key: yes
            serve-expired: yes
            so-reuseport: yes
            delay-close: 10000
            do-daemonize: no
            do-not-query-localhost: no
            neg-cache-size: 4M
            qname-minimisation: yes
            auto-trust-anchor-file: "var/root.key"
            chroot: "/opt/unbound/etc/unbound"
            harden-dnssec-stripped: yes
            harden-glue: yes
            private-address: 10.0.0.0/8
            private-address: 172.16.0.0/12
            private-address: 192.168.0.0/16
            private-address: 169.254.0.0/16
            private-address: fd00::/8
            private-address: fe80::/10
            private-address: ::ffff:0:0/96
            tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt
            unwanted-reply-threshold: 10000
            use-caps-for-id: yes
            val-clean-additional: yes

        remote-control:
            control-enable: no
