---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-mailserver.filter" . }}-headless
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: filter
spec:
  clusterIP: None
  type: ClusterIP
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.filter.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: filter
  ports:
    - name: controller
      port: 11334
      targetPort: 11334
      protocol: TCP
    - name: worker
      port: 11332
      targetPort: 11332
      protocol: TCP
