---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-mailserver.mda" . }}-headless
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: mda
spec:
  clusterIP: None
  type: ClusterIP
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.mda.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: mda
  ports:
    - name: imap
      port: 143
      targetPort: 143
      protocol: TCP
    - name: lmtp
      port: 2003
      targetPort: 2003
      protocol: TCP
    - name: auth
      port: 2004
      targetPort: 2004
      protocol: TCP
    - name: managesieve
      port: 4190
      targetPort: 4190
      protocol: TCP

