apiVersion: v2
name: docker-mailserver
description: Docker Mailserver based on the famous ISPMail guide. All images are
  based on Alpine Linux and are so small as possible.
sources:
- https://github.com/jeboehm/docker-mailserver
version: 0.2.57
keywords:
- postfix
- dovecot
- mail
- mailserver
- smtp
- imap
- docker-mailserver
- fetchmail
- rspamd
appVersion: 5.0.84
maintainers:
- name: jeboehm
dependencies:
- name: redis
  version: 20.13.4
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: redis.enabled
- name: mariadb
  version: 20.5.9
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: mariadb.enabled
- name: common
  version: 2.31.4
  repository: oci://registry-1.docker.io/bitnamicharts
annotations:
  category: Mail
  licenses: MIT
  images: |
    - name: mailserver-mta
      image: docker.io/jeboehm/mailserver-mta:latest
    - name: mailserver-mda
      image: docker.io/jeboehm/mailserver-mda:latest
    - name: mailserver-filter
      image: docker.io/jeboehm/mailserver-filter:latest
    - name: mailserver-web
      image: docker.io/jeboehm/mailserver-web:latest
    - name: mailserver-virus
      image: docker.io/jeboehm/mailserver-virus:latest
    - name: fetchmailmgr
      image: ghcr.io/jeboehm/fetchmailmgr:latest
    - name: redis
      image: docker.io/bitnami/redis:latest
