apiVersion: v2
name: docker-mailserver
description: Docker Mailserver based on the famous ISPMail guide. All images are based
  on Alpine Linux and are so small as possible.
sources:
- https://github.com/jeboehm/docker-mailserver
version: 0.0.16
keywords:
- postfix
- dovecot
- mail
- mailserver
- smtp
- imap
- docker-mailserver
appVersion: v4.2.3
maintainers:
- name: jeboehm
dependencies:
- name: redis
  version: 20.10.0
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: redis.enabled
- name: mariadb
  version: 20.4.1
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: mariadb.enabled
- name: common
  version: 2.30.0
  repository: oci://registry-1.docker.io/bitnamicharts
annotations:
  category: Mail
  licenses: MIT
  images: |
    - name: mailserver-mta
      image: docker.io/jeboehm/mailserver-mta:latest
    - name: mailserver-mda
      image: docker.io/jeboehm/mailserver-mda:latest
    - name: mailserver-filter
      image: docker.io/jeboehm/mailserver-filter:latest
    - name: mailserver-web
      image: docker.io/jeboehm/mailserver-web:latest
    - name: mailserver-virus
      image: docker.io/jeboehm/mailserver-virus:latest
    - name: redis
      image: docker.io/bitnami/redis:latest
