---

apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ printf "%s-configenv" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
    namespace: {{ include "common.names.namespace" . | quote }}
    labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 6 }}
    {{- if .Values.commonAnnotations }}
    annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 6 }}
    {{- end }}
data:
    MYSQL_DATABASE: {{ include "docker-mailserver.databaseName" . | quote }}
    MYSQL_USER: {{ include "docker-mailserver.databaseUser" . | quote }}
    MYSQL_HOST: {{ include "docker-mailserver.databaseHost" . | quote }}
    MYSQL_PORT: {{ include "docker-mailserver.databasePort" . | quote }}

    REDIS_HOST: {{ include "docker-mailserver.redisHost" . | quote }}
    REDIS_PORT: {{ include "docker-mailserver.redisPort" . | quote }}

    MDA_HOST: {{ printf "%s-headless" (include "docker-mailserver.mda" .) | quote }}
    MTA_HOST: {{ printf "%s-headless" (include "docker-mailserver.mta" .) | quote }}
    FILTER_HOST: {{ printf "%s-headless" (include "docker-mailserver.filter" .) | quote }}
    FILTER_VIRUS_HOST: {{ printf "%s-headless" (include "docker-mailserver.virus" .) | quote }}

    RSPAMD_HOST: {{ printf "%s-headless" (include "docker-mailserver.filter" .) | quote }} # TODO Obsolete
    MAILNAME: {{ .Values.config.mailname | quote }}
    POSTMASTER: {{ .Values.config.postmaster | quote }}

    RELAYHOST: "false"
    RELAY_OPTIONS: "false"
    RELAY_PASSWD_FILE: "false"

    FILTER_MIME: "false"

    ENABLE_IMAP: "true"
    ENABLE_POP3: "true"
    FILTER_VIRUS: "true"

    ENABLE_FTS: "true"
    FTS_ARGS: partial=3 full=20 verbose=0 lowmemory=256
    FTS_VSZ_LIMIT: 256M

    RECIPIENT_DELIMITER: {{ .Values.config.recipientDelimiter | quote }}
