---

name: Test Helm charts

on:
  pull_request:

jobs:
  test:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.x'
          check-latest: true

      - uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Bump Helm chart version
        if: steps.list-changed.outputs.changed == 'true'
        uses: explorium-ai/bump-helm-chart-action@main
        with:
          chart-path: charts/docker-mailserver
          level: patch

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      # - name: Create kind cluster
      #   if: steps.list-changed.outputs.changed == 'true'
      #   uses: helm/kind-action@v1.12.0

      # - name: Run chart-testing (install)
      #   run: ct install --chart-dirs=manifests
