name: Test Helm charts
on:
  pull_request:
env:
  CHART_PATH: charts/docker-mailserver
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: v3.17.0
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.x'
          check-latest: true
      - uses: helm/chart-testing-action@v2.7.0
      - name: Install chart dependencies
        run: |
          cd "$CHART_PATH"
          helm dependency build
      - name: Lint chart
        run: |
          cd "$CHART_PATH"
          helm lint .

# - name: Create kind cluster
#   if: steps.list-changed.outputs.changed == 'true'
#   uses: helm/kind-action@v1.12.0

# - name: Run chart-testing (install)
#   if: steps.list-changed.outputs.changed == 'true'
#   run: ct install --target-branch ${{ github.event.repository.default_branch }}
